- baseobject/_base.py
Removes the `TagAliaserMixin´ from the `BaseEstimator` as there are no tags to alias.
> [ENH] remove `TagAliaserMixin` from `BaseEstimator`

- README.md
- baseobject/_lookup.py
- pyproject.toml
This PR moves a slightly refactored lookup utility `all_estimators` over from `sktime`.
Changes are made to decouple the utility from:
* the base class registry. Instead, this is passed as an alias dictionary `class_dict`. Estimator types are now passed as classes directly, and can be passed as strings (like in `sktime`) if the alias dictionary is provided.
* `pandas`. This is now a soft dependency that is needed only when `as_dataframe` is set to `True`, allowing the `baseobject` package to not depend on `pandas`.
> [ENH] lookup utility `all_estimators`

- baseobject/_base.py
This PR robustifies `BaseObject.set_tags` against forgotten `__init__`, e.g., if a child object forgets to `super.__init__` (or intentionally does not call `super.__init__`).
Mirrors `sktime` https://github.com/alan-turing-institute/sktime/pull/3226
> [ENH] robustify `BaseObject.set_tags` against forgotten `__init__`

- baseobject/_lookup.py
This robustifies the `all_objects` exclusion behaviour, by avoiding to import excluded modules or their sub-modules on the `ignore_modules` list.
This is in particular relevant if such an import would lead to circular imports.
The change in logic is to avoid importing the ignored modules altogether, instead of importing and then discarding - the former avoids circular imports, the latter runs into the problem of circular imports, potentially.
Also see https://github.com/alan-turing-institute/sktime/pull/3198 in `sktime`.
> [ENH] robustify `all_objects` exclusion behaviour

- .github/workflows/wheels.yml
The release CI workflow for unix was breaking as it was running `make test`, but no `make` file was present. This is replaced by a direct `pytest` call.
> [ENH] fix unix wheel test in release workflow

- pyproject.toml
This fixes an error that is causing test failures in other PRs due to a reference to the baseobject package in the configuration for test coverage in the package's `pyproject.toml`. The reference to `baseobject` was updated to `skbase`. 
Also updated the excluded directories to exclude the docs and tests from coverage.
None.
Tests run successfully and decision on excluding tests and docs from coverage.
> Fix CI error from test coverage reference to old package name

- pyproject.toml
- skbase/_base.py
- skbase/testing/test_all_objects.py
- skbase/testing/utils/deep_equals.py
- skbase/testing/utils/tests/test_deep_equals.py
- skbase/tests/test_base.py
Fixes #55.
Updates known_first_party option in `pyproject.toml` isort config to be `skbase` not `baseobject`.
No.
This may trigger pre-commit.ci to fix the import sorting. Make sure that looks right if it happens.
> Update known_first_party option in isort config

- docs/source/conf.py
- skbase/tests/test_base.py
This includes 2 fixes to errors that were raised by #68. Fixing this will allow #68 to be merged.
Fixes call init on parent (BaseObject) in test classes. Also, updates conf.py to fix minor issues with unused variables.
> Fixes to issues identified by CodeQL Scanning

- skbase/testing/test_all_objects.py
This PR improves error messages in the `test_object_tags` interface contract test, adding the source class and specific reasons for failures.
Ports https://github.com/sktime/sktime/pull/4014
> [ENH] Improve error messages in `test_object_tags` test

- pyproject.toml
Bumps the upper `sklearn` requirement bound to `<1.3.0`.
Surely nothing bad will happen.
> [MNT] bump `sklearn` upper bound to `<1.3.0`

- skbase/base/_base.py
- skbase/testing/utils/deep_equals.py
- skbase/tests/test_base.py
Mirrors `sktime` PR https://github.com/sktime/sktime/pull/3862, partial towards #83
Description from `sktime` PR:
This adds an equality dunder to `BaseObject` descendants.
Two `BaseObject` descendants are considered equal if they define the same estimator blueprint, i.e., nested `get_params` result in value-identical dictionaries (with nested call to `__eq__` should those dictionaries contain `BaseObject` descendants).
Includes a test for expected properties of the dunder.
This is prompted by issues of equality testing in tests such as in the failure relevant for https://github.com/sktime/sktime/pull/3857, where equality currently means object identity rather than parameter identity.
> [ENH] Equality dunder for `BaseObject`-s

- skbase/base/_base.py
- skbase/tests/test_baseestimator.py
Uniform `get_fitted_params` interface for `BaseEstimator`, including tests.
Partially addresses #83.
Related `sktime` issues and PR:
* https://github.com/sktime/sktime/issues/971
* https://github.com/sktime/sktime/pull/3077
* https://github.com/sktime/sktime/issues/3381
* https://github.com/sktime/sktime/pull/3598
* https://github.com/sktime/sktime/issues/3645
> [ENH] `get_fitted_params` interface for `BaseEstimator`

- docs/source/about.rst
- docs/source/conf.py
- docs/source/contribute.rst
- docs/source/contribute/development.rst
- docs/source/contribute/development/developer_guide.rst
- docs/source/index.rst
- docs/source/user_documentation/user_guide.rst
- docs/source/user_documentation/user_guide/validate.rst
- docs/source/users.rst
- pyproject.toml
Fixes #50
Uses sphinx-design instead of sphinx-panel in the project's Sphinx docs. Sphinx-design provides a nicer design aesthetic and I believe sphinx-panel is no longer maintained.
sphinx-design is a new documentatino dependency (instead of sphinx-panel).
Do the affected documentation pages render correctly and are the panels "clickable".
> Convert about page to sphinx-design

- skbase/testing/utils/_dependencies.py
This PR removes `sktime` references from docstrings and error messages in the dependency checkers, and streamlines the message generation logic a bit.
> [ENH] remove `sktime` references from dependency checkers

- skbase/testing/test_all_objects.py
This PR changes the name of the `return_exceptions` argument in `QuickTester.run_tests` to `raise_exceptions`. Parallels https://github.com/sktime/sktime/pull/4030, see there for reasoning why.
This PR is without deprecation (since we can still avoid it).
> [ENH] in `QuickTester.run_tests`, rename `return_exceptions` argument to `raise_exceptions`

- skbase/__init__.py
- skbase/base/_meta.py
- skbase/tests/conftest.py
This removes deprecation added in prior PR refactoring the package to `skbase.base`, `skbase.looup`, `skbase.validate` and `skbase.testing` modules.
The package will use deprecation in the future (likely within the next few releases), but this early in the development is not going to.
> Remove deprecation

- .pre-commit-config.yaml
There was a commit in `pydocstyle` v6.2.3 that has since been reverted. Version 6.2.4 has not yet been released, so this reverts back to 6.2.2.
Also updating additional dependency section to make use of extra dependency installation. Note that `pydocstyle` switched to using tomli/tomllib for toml parsing instead of toml. Their "extra" install maps this automatically.
> Update pydocstyle in pre-commit config

- .pre-commit-config.yaml
- setup.cfg
- skbase/base/_base.py
- skbase/base/_meta.py
- skbase/lookup/_lookup.py
- skbase/testing/utils/_dependencies.py
- skbase/testing/utils/deep_equals.py
Fixes error in #119.
There were changes in a few of the linters used in `skbase`'s continuous integration process.
- `pydocstyle` moved to the use of `tomli` or `tomllib` for parsing pyproject.toml files (we are going to use `tomli` since `tomllib` is not available in older Python versions)
- `flake8-bugbear` validation B028 was catching cases of manual quotes in string formatting. It caused #119 to fail. `flake8-bugbear` has since moved this to an optional validation. This enables that validation, along with two others. And fixes the resulting items flagged by the CI.
- Note that B028 was changed to B907. And optional validations B03 and B904 were also turned on.  `flake8-bugbear` [readme](https://github.com/PyCQA/flake8-bugbear) has a description. This PR includes fixes issues …
> [MNT] Handle updates to pre-commit linters

- skbase/base/_base.py
Adds an `skbase` native `get_params` to `BaseObject` which replaces the `sklearn` based one. Fixes #116.
The new `get_params` is largely based on the `sklearn` one, with minor changes (better docstring, dependency on `skbase` methods).
As far as I can see, this removes the last logical dependency on `sklearn` `BaseEstimator`.
Credit should already be given through the blanket reference to `sklearn` `BaseEstimator`.
Pretty printing and pretty display still constitute `sklearn` dependencies of `BaseObject`.
> [ENH] `skbase` native `get_params`

- skbase/lookup/_lookup.py
`all_objects` in vanilla form returns a list of `(str, BaseObject)` pairs.
Currently, these pairs do not need to satisfy the condition that for the pair `(name, klass)` it holds that `name` = `klass.__name__`.
An example of this case is when a class is assigned to a variable name other than the class name. In that case `name` is the variable name, not the class name. E.g., doing sth like this
```python
class Test:
def __init__(self, stuff):
more_stuff
test2 = Test
```
results in the class `Test` being returned twice, once with name `test2` and once with name `Test`.
This can be quite confusing and violate an interface contract that is not strictly stated as guaranteed, but may be assumed by users of the utility (and, apparently, by the status quo in `sktime` as well as the failing tests …
> [ENH] ensure that `all_objects` always returns (class name/class) pairs

- pyproject.toml
This PR adds `numpy` as a soft dependency, see discussion in https://github.com/sktime/skbase/pull/111.
It should be noted that this will have an effect only once the `sklearn` dependency is removed or moved to be a soft dependency, as `numpy` is a core dependency of `sklearn`.
> [MNT] numpy as a soft dependency

- skbase/tests/conftest.py
- skbase/utils/_iter.py
- skbase/utils/tests/test_iter.py
- skbase/validate/_types.py
- skbase/validate/tests/test_type_validations.py
Fixes #129. 
Error referenced in #129  was being raised through `skbase.utils.check_sequence`. This cleans up the error messaging there and in other type checking utility functions. They now raise `TypeError`s and use a utility function to remove boilerplate "<class >" when converting classes to strings.
None.
Change in error messages.
> [BUG] Fix type error bug

- skbase/base/_base.py
- skbase/lookup/_lookup.py
- skbase/testing/utils/_dependencies.py
`flake8` raises a warning for calls to `warnings.warn` that don't specify the `stacklevel` parameter. `stacklevel` controls where the warning is shown from. Using ``stacklevel=2`` raises the warning at the code 1-level above the `warnings.warn` call, which seems like a reasonable default.
> Add stacklevel to warnings.warn calls

- docs/source/api_reference.rst
- skbase/base/_meta.py
- skbase/tests/conftest.py
- skbase/utils/__init__.py
- skbase/utils/_iter.py
- skbase/utils/_nested_iter.py
- skbase/utils/tests/test_iter.py
- skbase/utils/tests/test_nested_iter.py
Completes the portion of #49 and #19 for the `skbase.utils` submodule. Note that I've included docstring examples for the functions even if they aren't public because I think it is helpful for developers to be able to get a quick glimpse of what the function does.
Also updates names of functions to be non-public (I'm guessing we don't want them in user API) and make minor tweaks to make functions more robust or generalizable (as discovered during test creation).
The changes reflect:
- Adding basic tests of `skbase.utils` (functions are tested further in tests of their downstream uses)
- Improved docstrings of `skbase.utils` functionality (I believe these all now comply with `numpydoc` standard and have examples)
- Renamed functions to be non-public and updated the names in import …
> [ENH] Improve `skbase.utils`

- skbase/validate/_named_objects.py
- skbase/validate/tests/test_iterable_named_objects.py
Fixes #135
Allows users to specify a specific class type to be used in the named object checks (`is_sequence_named_objects` and `check_sequence_named_objects`. 
No
> Add object_type param to named object check

- skbase/testing/test_all_objects.py
This PR fixes an unreported return type bug of `BaseFixtureGenerator.is_excluded` which should return a boolean.
If `self.excluded_tests` is `None`, it returns a list rather than a boolean.
Also adds related detail comments about expected types of class attributes, as comments next to the class attribute definition.
> [BUG] fix unreported return type bug of `BaseFixtureGenerator.is_excluded`

- skbase/base/_base.py
- skbase/base/_tagmanager.py
- skbase/tests/conftest.py
port of https://github.com/sktime/sktime/pull/3630 to `skbase`
This PR factors out the tag management logic into a `_FlagManager` mixin, and generalizes the functionality so it can be used for multiple fields of tags.
Advantages:
* increases cohesion and reduces coupling, separates concerns in the `BaseObject` class: state/parameter management and tag management
* prepares the ground for managing configuration fields, e.g., for implementing a `set_config` similar to the new `sklearn` feature
Test coverage is already there for the base case, but should be added for a different tag field. Will do that with the PR that adds config handling.
(I called the flag manager since not all flags are tags, and interactions with the sklearn `_get_tags`)
A STEP is available here: …
> [ENH] tag manager mixin

- skbase/base/_base.py
- skbase/tests/conftest.py
- skbase/tests/test_base.py
port of https://github.com/sktime/sktime/pull/3822 to `skbase`
This PR adds a config management capabilities to all `sktime` objects, similar to `sklearn`'s new config interface, via two methods `get_config` and `set_config`.
It is based on the flag manager mixin introduced in https://github.com/sktime/sktime/pull/3630 (ported to `skbase` in https://github.com/sktime/skbase/pull/138)
A STEP is available here: https://github.com/sktime/enhancement-proposals/pull/29
Includes:
* test for `get_config` and `set_config` interface
> [ENH] object config interface

- skbase/testing/test_all_objects.py
This syncs `TestAllObjects` with the current `sktime` state:
* added docstrings
* some descriptive error messages
* sharper logic in testing the output of `clone` in `test_clone`
> [ENH] sync `TestAllObjects` with `sktime`

- skbase/base/_meta.py
- skbase/base/_pretty_printing/_object_html_repr.py
This fixes a bug with the html display for meta-objects, where any attempt to display an `skbase` meta-object would crash.
The reason was an import of `VisualBlock` from sklearn rather than skbase, which had an `estimator` parameter rather than the `obj` parameter which was expected.
We'll have to investigate why this was not tested.
> [BUG] fix html display for meta-objects

- pyproject.toml
This removes `skbase`'s dependency on `pytest` which should not be required.
`pytest` is still required in the developer dependency set.
Rationale is minimizing dependencies.
E.g., `sktime` would otherwise incur a new core dependency, `pytest` - this violates the original intention of this being a pure refactor.
> [MNT] remove `pytest` dependency

- .github/workflows/test.yml
This removes the `fail-fast` flag in CI, as the matrix runs concurrently and, usually, when one parallel task fails the next one is almost done already. Further, these take only few minutes to run, so should be no resource blocker.
> [MNT] remove `fail-fast` flag in CI

- .github/workflows/test.yml
- pyproject.toml
- skbase/base/_base.py
- skbase/testing/test_all_objects.py
- skbase/tests/test_base.py
- skbase/tests/test_meta.py
This PR removes `scikit-learn` as a dependency, including the remaining loci of coupling.
* in `BaseObject`, `scikit-learn` was still used in `clone`. This has been replaced with a constructor call, and checks that the tests expect. A config has been added that allows to skip these checks.
* in various tests, `scikit-learn` `clone` was still imported, this is useful for checking compatibility. Here, the imports have been isolated inside the tests, so the import is executed only in CI when the `dev` dependency set is installed. In a case where not, the tests are not executed.
* `BaseObject` was still inheriting from `sklearn` `BaseEstimator`,  but this should be unnecessary as all has been overridden now. This was removed, and tests for MRO adjusted.
* `joblib` has been imported in the …
> [MNT] remove `scikit-learn` as a dependency

- pyproject.toml
This explicitly adds `sklearn` to `tests` dependency set, as it is required in some tests for compatibility.
> [MNT] add `sklearn` to `test` dependency set

- pyproject.toml
the `skbase` documentation currently does not build due to conflicting requirements in the `docs` dependency set.
The error is this:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sphinx-rtd-theme 1.2.0 requires docutils<0.19, but you have docutils 0.19 which is incompatible.
```
This PR resolves the problem by copy-pasting the dependency set from `sktime`.
> [MNT] resolve dependency conflict in `docs` requirements

- docs/source/user_documentation/changelog.rst
- pyproject.toml
- skbase/validate/_types.py
This fixes some outdated pointers to the old repository name and the old pypi name (both `baseobject`), on the changelog documentation page.
Also fixes a linting complaint by the precommit.
> [DOC] fix some broken doc links, linting

- skbase/base/_base.py
- skbase/tests/test_base.py
This PR turns off the check in `BaseObject.clone`, which unintentionally couples `clone` to `pytest`, via import of `deep_equals` that imports `pytest` by accident (through `__init__`).
This can be done without deprecation, ahead of a refactor that moves `deep_equals` out of the `testing` module.
Fast fix for https://github.com/sktime/skbase/issues/177 but does not address it finally (if `check_clone` config is `True`, the bug still occurs)
> [ENH] turn off check in `BaseObject.clone`

- .github/workflows/test.yml
- skbase/_nopytest_tests.py
- skbase/tests/conftest.py
This adds basic tests to ensure isolation from developer dependencies including `pytest` outside of test modules, and adds a basic `pytest`-less test for `BaseObject`.
The approach is as follows:
* addition of a new GHA job
* only `skbase` plain is installed, no `dev` dependencies
* a test file `_nopytest_tests` is added, which can contain `pytest`-free checks
* `all_objects` plain is executed. As this crawls all modules (except tests and a few others), it will spot unisolated developer dependency imports
* parameterless methods of `BaseObject` are executed on an instance. This ensures those methods are isolated, and it would also catche the issue with `clone` described here: https://github.com/sktime/skbase/issues/177
> [MNT] test for isolation of developer dependencies, and basic `pytest`-less test for `BaseObject`

- skbase/_nopytest_tests.py
This adds more methods (those that require args) to the no-`pytest` test of method calls, extending coverage in the case of no developer dependencies installed.
> [ENH] add args to the no dev deps base test

- docs/source/about/governance.rst
- docs/source/about/team.rst
- pyproject.toml
- skbase/__init__.py
This PR updates project information in the docs and `__init__`:
* the package now points to `sktime`, as being part of `sktime` and being maintained by the `sktime` team, in relevant places - sphinx docs (governance, team), and `pyproject.toml`
* in particular, it is no longer a separate entity per the docs, as the single active CC member (of `skbase`) I don't think that makes sense - especially since it receives most occasional fixes from `sktime` maintainers
* the version string in the package `__init__` was not up-to-date with the `pyproject.toml`, this is fixed.
Fixes #189 in passing (I think all instances are removed or superseded by this)
> [DOC] update project metadata, point governance to `sktime`, update `__init__` info 

- skbase/lookup/_lookup.py
This fixes the faulty `suppress_import_stdout` in `all_objects`.
Instead of always restoring the `stdout` after suppression to its initial state, it would instead set it to the terminal, no matter where it previously was (e.g., a jupyter notebook).
Further, it would also not be reset if an exception was encountered, which is now also handled.
This fixes the error in https://github.com/sktime/sktime/issues/4692 by manual testing, although I'm not sure how one would test for this in CI.
> [BUG] fix faulty `suppress_import_stdout` in `all_objects`

- skbase/base/_base.py
- skbase/tests/test_base.py
The `clone` method of `BaseObject` would not properly clone `sklearn` estimator that are components (which do not have their own `clone`).
For now, this is fixed by replacing the faulty `skbase` `clone` with a copy of the `sklearn` `clone`.
> &hazrulakmal [BUG] fix `clone` for nested `sklearn` estimators

- .github/workflows/test.yml
- .github/workflows/wheels.yml
- README.md
- docs/source/_static/switcher.json
- docs/source/get_started.rst
- docs/source/user_documentation/changelog.rst
- docs/source/user_documentation/installation.rst
- pyproject.toml
Maintenance release 0.5.0 for python 3.7 end-of-life.
Python 3.7 is removed from:
* package metadata, support
* estimator metadata
* CI and tests
* documentation
> Release 0.5.0

- README.md
minor updates to landing pages:
* clarification to content of skbase
* link to tutorials
> [DOC] landing page updates

- .github/workflows/test.yml
Fixes https://github.com/sktime/skbase/issues/208, by replicating the `sktime` setup, which separates windows CI and unix based CI.
> [MNT] separate windows CI element from unix based CI

- pyproject.toml
In https://github.com/sktime/skbase/pull/205, `pre-commit` CI seems to complain that the `extend-exclude` parameter is not followed by a string (but a list of strings).
Attempting to fix this by changing the list of strings into a single string tha should hopefully comply with the expected syntax.
> [MNT] convert `black` `extend-exclude` parameter to single string

- skbase/__init__.py
The version in `__init__` has not been properly updated - this PR fixes that.
Upon 0.5.1 or 0.6.0, a replacefrom 0.5.0 should ensure consistencyl
> [MNT] update `__init__` version

- skbase/testing/test_all_objects.py
This PR removes the `sklearn` dependency in `get_test_params`, by replacing `_check_get_params_invariance` with an `skbase`-native implementation.
The call to `clone` is replaced with the object's own `clone`method.
> [ENH] remove `sklearn` dependency in `test_get_params`

- skbase/testing/test_all_objects.py
- skbase/testing/utils/tests/__init__.py
- skbase/tests/test_base.py
- skbase/utils/dependencies/tests/__init__.py
- skbase/utils/dependencies/tests/test_check_dependencies.py
- skbase/utils/tests/test_deep_equals.py
This PR moves the tests for dependency checks and `deep_equals` to the `utils` module where those utilities reside.
> [ENH] move tests for dependency checks and `deep_equals` to `utils` module

- skbase/base/__init__.py
- skbase/base/_meta.py
- skbase/tests/conftest.py
This PR adds meta-object mixins - previously, the package provided only classes inheriting from `BaseObject` or `BaseEstimator`, which can create multiple inheritance conflicts if downstream needs to inherit from an abstract desceendant of `BaseObject` or `BaseEstimator`.
This is also more in line with the actual use cases in `sktime` and `skpro`.
> [ENH] meta-object mixins

- docs/source/about/governance.rst
- docs/source/about/history.rst
- docs/source/about/mission.rst
- docs/source/about/roadmap.rst
- docs/source/conf.py
- docs/source/contribute/code_of_conduct.rst
- docs/source/contribute/development/developer_guide/git_workflow.rst
- docs/source/contribute/development/developer_guide/release_instructions.rst
- docs/source/contribute/how_to_contribute.rst
- docs/source/user_documentation/installation.rst
This PR updates some `sktime` links to their correct locations after change of the webdomain.
> [DOC] update `sktime` links

- skbase/lookup/_lookup.py
`load_module` is deprecated and will be replaced by `exec_module` in python 3.12, this PR addresses that.
The fix is highly nontrivial - the crucial line was
`imported_mod = module.load_module()` for a `module: SourceFileLoader`,
which had to be replaced by the equivalent four (!) lines
```python
spec = importlib.util.spec_from_file_location(module.name, module.path)
imported_mod = importlib.util.module_from_spec(spec)
loader = spec.loader
loader.exec_module(imported_mod)
```
The deprecation message raised by `load_module` is highly unhelpful, and I had to reverse engineer this from a very helpful PR in `nox`, https://github.com/wntrblm/nox/pull/498
> [MNT] address deprecation of `load_module`

- .github/workflows/test.yml
- .github/workflows/wheels.yml
Makes a number of improvements to the test CI:
* Simplifies test CI matrix
* removes `conda` dependency
* upgrades checkout action to v4
> [MNT] simplify test CI and remove `conda`

- .github/workflows/test.yml
- .github/workflows/wheels.yml
- README.md
- docs/source/get_started.rst
- docs/source/user_documentation/installation.rst
- pyproject.toml
This PR adds python 3.12 in the `pyproject.toml`, project documentation, and CI.
For release with 0.6.0
> [MNT] python 3.12

- skbase/testing/test_all_objects.py
This corrects the parameter name in `TestAllObjects` `all_objects` call, from `exclude_estimators` to `exclude_objects`.
> [BUG] correct parameter name in `TestAllObjects` `all_objects` call

- skbase/lookup/tests/test_lookup.py
So far, `test_get_package_metadata_returns_expected_results` has failed in every attempt to make a proper PR to `scikit-base`, due to the design decision of using the package itself as a test case for `all_objects` - so adding any function or class anywhere without making a corresponding change in a register will fail the test.
Apart from that this needs to change, as a short term measure a more helpful error message should allow developers to find the place to add the expected functions or classes.
This PR adds these error messages.
> [ENH] informative failure message in `test_get_package_metadata_returns_expected_results`

- skbase/base/_base.py
- skbase/tests/test_base.py
Mirror of https://github.com/sktime/sktime/pull/2931
This PR introduces experimental functionality to `set_params` to enable it to recognize unique suffixes as aliases for full parameter strings.
That is, in the example in https://github.com/alan-turing-institute/sktime/discussions/2929, it enables `set_params` - and, in consequence, the `param_grid` of grid search - to recognize `max_depth` instead of `forecaster__forecast__estimator__max_depth`. 
This is primarily meant as convenience sugar for the user of grid search or, more generally, `set_params`.
Contains tests for both nested parameter setting behaviour, as well as parameter key aliasing in nested composites.
> [ENH] `set_params` to recognize unique suffixes as aliases for full parameter string

- .readthedocs.yaml
- skbase/utils/tests/test_check.py
- skbase/utils/tests/test_deep_equals.py
This PR solves the readthedocs build issue by:
* isolating some `numpy` imports
* adding the test dep set as required for readthedocs builds to avoid import failures (pytest)
> [ENH] address readthedocs build failures

- skbase/utils/deep_equals/_deep_equals.py
- skbase/utils/tests/test_deep_equals.py
This PR fixes an unreported bug that prevented `deep_equals` plugins to be passed in some recursions.
The recursions have been fixed, and test cases have been added.
> [BUG] ensure `deep_equals` plugins are passed on to all recursions

- SECURITY.md
- docs/source/about/governance.rst
- docs/source/conf.py
- docs/source/contribute/code_of_conduct.rst
- docs/source/contribute/development/developer_guide/creating_docs.rst
- docs/source/contribute/development/developer_guide/dependencies.rst
- docs/source/contribute/development/reviewer_guide.rst
- docs/source/user_documentation/changelog.rst
- enhancement_proposals/sbep_1.md
- skbase/__init__.py
- skbase/_exceptions.py
- skbase/base/__init__.py
- skbase/base/_base.py
- skbase/base/_meta.py
- skbase/base/_pretty_printing/_object_html_repr.py
- skbase/base/_tagmanager.py
- skbase/lookup/_lookup.py
- skbase/lookup/tests/test_lookup.py
- skbase/tests/mock_package/test_mock_package.py
- skbase/tests/test_base.py
- skbase/tests/test_baseestimator.py
- skbase/tests/test_meta.py
- skbase/utils/_check.py
- skbase/utils/_iter.py
- skbase/utils/deep_equals/_deep_equals.py
- skbase/utils/tests/test_iter.py
- skbase/validate/_named_objects.py
- skbase/validate/_types.py
- skbase/validate/tests/test_iterable_named_objects.py
Commands used:
1. `codespell --write-changes .`
2. `typos --locale en --write-changes`
> [MNT] Fixed spelling mistakes as identified by `codespell` and `typos`

- skbase/utils/deep_equals/_deep_equals.py
- skbase/utils/tests/test_deep_equals.py
This PR improves error messaging in `deep_equals` - providing a clearer return on `pd.DataFrame` `dtypes` no being equal.
Mirror of https://github.com/sktime/sktime/pull/5560, for links to `sktime` `dask` failures see there.
> [ENH] `deep_equals` - clearer return on `pd.DataFrame` `dtypes` not being equal

- skbase/utils/deep_equals/_deep_equals.py
- skbase/utils/tests/test_deep_equals.py
The `deep_equals` plugin fo `pd.Index` resulted in failure when checking equality.
This PR fixes the bug, and adds test cases.
> [BUG] fix `deep_equals` plugin for `pd.Index`

- skbase/base/_base.py
- skbase/tests/test_base.py
This PR changes logic that ensures we retain config at `reset`.
Tests for `set_config`, `get_config` are also added to ensure coverage.
> [ENH] retain config at `reset`, add tests for `set_config`, `get_config`

- docs/source/_static/switcher.json
- docs/source/user_documentation/changelog.rst
- pyproject.toml
- skbase/__init__.py
Release 0.7.0
* changelog
* version bump
> Release 0.7.0

- skbase/utils/deep_equals/_deep_equals.py
- skbase/utils/tests/test_deep_equals.py
This PR fixes an unreported bug where `deep_equals` would break on `np.array` with `dtype="object"`, this is due to the `equal_nan=True` setting in `np.array_equal` which will lead to an exception if dtype="object"`.
Also includes test cases covering this.
Mirror of https://github.com/sktime/sktime/pull/5697 (duplicated prior to ongoing refactor)
> [BUG] fix `deep_equals` for `np.array` with `dtype="object"`

- .all-contributorsrc
- skbase/base/_base.py
- skbase/tests/test_base.py
Fixes https://github.com/sktime/skbase/issues/276
Please refer to: https://github.com/sktime/skbase/issues/276
No
The `_clone()` method has a `# copied from sklearn` comment above it. Any concerns with modifying this method? Any alternative solutions come to mind?
> [BUG] Fix cloning of config for nested objects

- skbase/lookup/_lookup.py
Currently, `all_objects` breaks if `filter_tags` is set and some tags in estimators are lists, as lists are unhashable.
This PR changes behaviour in the case of iterable tag value from raising an exception (unhashable list) to the condition that at least one search value is among the tag values.
Fixes first item in https://github.com/sktime/sktime/issues/5755
> [ENH] `all_objects` `filter_tags` to function with list-of tags

- skbase/base/_base.py
- skbase/tests/conftest.py
- skbase/utils/__init__.py
- skbase/utils/random_state.py
- skbase/utils/tests/test_iter.py
- skbase/utils/tests/test_nested_iter.py
- skbase/utils/tests/test_random_state.py
- skbase/utils/tests/test_utils.py
Adds a method `set_random_state` to estimators, and a utilities module related to random state handling.
The `set_random_state` method is recursive and creates dependent random seeds, similar to the `sklearn` utility of the same name.
In slight departure from `sklearn`, this is added as a method of `BaseObject`, similar to `clone`.
> [ENH] Random state handling, `set_random_state` method

- skbase/lookup/_lookup.py
This PR extends `all_objects` to allow an arbitrary base class - currently, it only lists classes inheriting from `skbase` `all_objects`. With the change in this PR, something like this will give the expected results - of all estimators in `sklearn`:
```python
from skbase.lookup import all_objects
from sklearn.base import BaseEstimator
all_objects(BaseEstimator, package_name="sklearn", modules_to_ignore=["tests"], as_dataframe=True)
```
Minor changes also contained:
* removes unused args `exclude_estimators` and `ignore_modules`
> [ENH] allow arbitrary base class in `all_objects`

- skbase/base/_base.py
This PR improves the developer experience for handling the test instance generation of `BaseObject`:
* improved exception messages clarifying reason of failure if `create_test_instance` or `create_test_instances_and_names` is called
* extension of `get_test_params` to allow cases where not all `__init__` params have defaults
> [ENH] improved exception feedback for test instance generation methods of `BaseObject`

- skbase/tests/conftest.py
- skbase/utils/dependencies/__init__.py
- skbase/utils/dependencies/_dependencies.py
This PR moves the `_check_estimator_deps` utility to `skbase`, from `sktime`.
It also makes minor updates to the other utilities in `skbase.utils.dependencies`.
> [ENH] estimator soft dependency check utilities

- .all-contributorsrc
From #289, the update to the contributors file was valid due to earlier contributions.
> [MNT] add yarnabrina to `all-contributorsrc`

- skbase/base/_base.py
Minor doc fix, removes accidental duplicated section in `get_test_params` docstring
> [DOC] remove accidental duplicated section in `get_test_params` docstring

- skbase/base/_base.py
PR #239 changes the type of exception raised by `get_test_params` to `ValueError`, which is an unintended side effect of the imprroved error feedback.
This can lead to breakage in exception handling, e.g., in `sktime` tests for exception handling on top.
This PR ensures the type of exception is preserved.
> [BUG] preserve exception type raised by `get_test_params`

- skbase/tests/conftest.py
- skbase/utils/deep_equals/_deep_equals.py
- skbase/utils/dependencies/_dependencies.py
- skbase/utils/tests/test_deep_equals.py
Fixes #302 by using a safe way to read length.
Also adds the MRE #302 as a test case, to cover this edge case.
FYI @MBristle, and we thought the fix was easy...
> [BUG] fix `deep_equals` on objects which have `__len__` but `len(obj)` causes exception

- skbase/base/_pretty_printing/_object_html_repr.py
- skbase/base/_pretty_printing/tests/__init__.py
- skbase/base/_pretty_printing/tests/test_pprint.py
Fixes https://github.com/sktime/skbase/issues/309, by reverting the name of the `objs` attribute to `estimators`, the same as for `sklearn`.
This ensures that `sktime` objects are displayed correctly as components of `sklearn` objects when displayed as html figure.
Also adds a test, and cleans up docstrings.
> [BUG] fix `sklearn` compatibility of `_VisualBlock`

- skbase/tests/conftest.py
- skbase/utils/deep_equals/_deep_equals.py
This PR replaces a comparison in `deep_equals` with a defensive alternative.
Namely, `np.any(x != y)` and similar expressions are assumed to result in a boolean, but this may be false in pathological cases, e.g., nested lists or nested numpy arrays with non-numpy objects inside.
The defensive replacement should catch any case where the expressions assumed boolean are not boolean, and in that case have the same effect as skipping the test.
If `deep_equals` cannot determine equality via the condition, it returns `True` at the end, so when in doubt objects and estimators are deemed to comply with `sklearn` or `sktime` contracts, in dependent tests.
> [BUG] safer comparison in `deep_equals` if `np.any(x != y)` does not result in boolean

- skbase/lookup/_lookup.py
- skbase/lookup/tests/test_lookup.py
- skbase/tests/conftest.py
This fixes https://github.com/sktime/skbase/issues/327, which caused a permanently muted `stdout` after `all_objects` call.
The bug was due to the `sys.stdout` not being properly reset after muting, in one of two instances where this was done.
This PR also replaces both instances with a muter context manager - the implementation of the muting was a bit brittle, relying on manual try/except and temp stdout handling which is risky.
Includes a test that the `sys.stdout` is indeed unchanged.
> [BUG] fix permanently muted `stdout` after `all_objects` call

- skbase/lookup/_lookup.py
- skbase/tests/conftest.py
This PR refactors `all_objects` to be less convoluted and for improved efficiency.
Makes the following changes:
* simplifies input coercions and context manager handling
* factors out the central walk loop into an `lru_cache`-d function
* for this, some arguments are coerced to `tuple` to ensure hashability
* further small refactoring to make the function clearer to read
The behaviour of the function `all_objects` should be unaffected, this is a clean refactor.
> [ENH] refactor - simplify `all_objects` logic and add cache for efficient lookup

- skbase/lookup/_lookup.py
- skbase/lookup/tests/test_lookup.py
This PR closes https://github.com/sktime/skbase/issues/326.
It implements:
* functionality for `all_objects` to retrieve classes by specifying regex for tag values
* deprecation warnings for `str` and `list of str` condition meaning to change from "has tag" to "tag is True" meaning, from 0.9.0 release onwards
* the deprecation message includes instructions on how to retain current behaviour - this uses the regex specification
This PR also improves formatting of the docstring of `all_objects`.
> [ENH] `all_objects` retrieval filtered by regex applied to tag values, deprecation of "has tag" condition in favour of "tag is True"

- skbase/validate/tests/test_type_validations.py
`skbase` does not have any core dependencies, but some tests were depending on `numpy`, for example cases in which dependent code was constructed that was also using `numpy`.
This PR fixes some incompatibility issues in that code, with the newly released `numpy 2`.
> [MNT] `numpy 2` compatibility of some tests

- skbase/base/_base.py
- skbase/tests/test_base.py
Currently, there is no easy method to return a `BaseObjects`'s parameter name in the same order as they appear in the `__init__`, which is useful in various situations. This is because `get_param_names` does retrieve them, but sorts them alphabetically before returning.
The default should be not sorting, as sorting is an easy operation for the user, whereas retreving the parameters manually is hard.
This PR therefore introduces a new bool parameter `sorted` to `get_param_names` which allows the user to specify whether they want the name sorted.
> [ENH] option to return `BaseObject.get_param_names` in the same order as in the `__init__`

- skbase/lookup/_lookup.py
- skbase/tests/conftest.py
- skbase/utils/dependencies/_dependencies.py
- skbase/utils/stdout_mute.py
Minor refactor in anticipation of external and further internal usage - moves `StdoutMute` context manager to a submodule of `utils`.
Also refactors manual `stdout` handling in `_check_soft_dependencies` to use the utility.
> [ENH] refactor - move `StdoutMute` context manager to `utils`

- skbase/tests/conftest.py
- skbase/utils/dependencies/_dependencies.py
The `_check_soft_dependencies` utility had inefficiencies and side effects, because to check the soft dependency being present, an import would be attempted, which can lead to circular imports or casacding imports.
This PR replaces the logic with an import-free check.
It also deprecates the argument `suppress_import_stdout`, as there is no longer any import, hence no `stdout` output that would be created.
Mirror of https://github.com/sktime/sktime/pull/6355 which includes contributions by @yarnabrina, and of https://github.com/sktime/sktime/pull/6719
> & yarnabrina [ENH] prevent imports in `_check_soft_dependencies`

- .github/workflows/wheels.yml
- docs/source/user_documentation/changelog.rst
v11 is not available any more
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#standard-github-hosted-runners-for-public-repositories
@fkiraly those jobs do not start
https://github.com/sktime/skbase/actions/runs/10212328626
> [MNT] Move release CI to macos-12 image

- .github/workflows/wheels.yml
See the warning in runs
https://github.com/sktime/skbase/actions/runs/10213897671/job/28260425947#step:4:1
Docs: https://github.com/pypa/gh-action-pypi-publish?tab=readme-ov-file#customizing-target-package-dists-directory
> [MNT] release workflow: Upgrade deprecated pypa action parameter

- skbase/utils/dependencies/_dependencies.py
Mirror bugfix of https://github.com/sktime/sktime/pull/6986 in preparation of deduplication refactor.
> &toandaominh1997 [BUG] fix dependency checkers in case of multiple distributions available in environment, e.g., on databricks

- skbase/base/_base.py
This PR makes the `get_fitted_params` core functionality and defaults safer against exceptions on `getattr`.
In rare cases, `getattr` can cause an exception, namely if a property is being accessed in a way that generates an exception.
Examples are some fitted parameter arguments in `sklearn` that are decorated as property in newer versions, e.g., `RandomForestRegressor.estimator_` in unfitted state.
In most use cases, there will be no change in behaviour; in the described case where an exception would be raised, this is now caught and suppressed, and the corresponding parameter is considered as not present.
Changes occur only in cases that would have previously raised genuine exceptions, so no working code is affected, and no deprecation is necessary despite this being a change to a core …
> [ENH] safer `get_fitted_params` default functionality to avoid exception on `getattr`

- skbase/lookup/_lookup.py
- skbase/lookup/tests/test_lookup.py
- skbase/tests/conftest.py
Carries out deprecations and change actions scheduled for 0.9.0:
* change of `all_objects` `filter_tags` argument behaviour for `str` and iterable of `str` to mean tags with value `True`
> [MNT] 0.9.0 deprecations and change actions

- skbase/testing/test_all_objects.py
This adds a test that calling `_repr_html_` of any object does not crash.
This adds coverage for the failure case in https://github.com/sktime/sktime/pull/7043.
Mirror of https://github.com/sktime/sktime/pull/7151, closes #357
> [ENH] add test that html repr of objects does not crash

- skbase/base/_base.py
This adds the ability to the `clone` methods to also clone nested `dict`-s.
Closes #280, see https://github.com/sktime/skbase/issues/280#issuecomment-2366869402
> [ENH] `clone` method to handle nested `dict`

- skbase/utils/dependencies/_dependencies.py
Carries out deprecations and change actions scheduled for 0.10.0:
* in `_check_soft_dependencies`, remove `suppress_import_stdout` arg
> [MNT] 0.10.0 deprecations and change actions

- skbase/base/_pretty_printing/tests/test_pprint.py
- skbase/tests/test_base.py
- skbase/utils/tests/test_deep_equals.py
This PR updates the `sklearn` soft dependency checks via `_check_soft_dependencies`to use the PEP 440 name, `scikit-learn`.
> [MNT] updates `sklearn` soft dependency checks to use PEP 440 name

- .github/workflows/test.yml
- pyproject.toml
Adds experimental 3.13 wheels and testing on 3.13-rc.2, ahead of the 3.13 release early Oct 2024.
Full 3.13 support should be released with 0.11.0 only.
Towards https://github.com/sktime/skbase/issues/367
> [MNT] python 3.13 wheels and 3.13-rc.2 testing

- skbase/base/_base.py
This merges some minor improvements from `sktime` `BaseEstimator` into `skbase` `BaseEstimator`:
* docstring formatting
* clearer error messages
* deduplicating logic with `check_is_fitted` calls
Accompanies https://github.com/sktime/sktime/pull/7213, see there for explanation of merge and deduplication.
> [ENH] merge `sktime` `BaseEstimator` into `skbase` `BaseEstimator`

- .github/workflows/test.yml
- .github/workflows/wheels.yml
- README.md
- docs/source/get_started.rst
- docs/source/user_documentation/installation.rst
- pyproject.toml
Python 3.8 has reached end-of-life, that is addressed in this PR:
* removal of python 3.8 from package support tags
* removal of python 3.8 from CI
* removal of python 3.8 support references from documentation
In some of the above places, python 3.13 was not present, in those cases python 3.13 was also added.
> [MNT] manage python 3.8 end-of-life

- skbase/base/_base.py
Adds a `_get_clone_plugins` method to `BaseObject` to allow packages to override the `clone` logic with custom plugins.
> [ENH] add `_get_clone_plugins` to allow packages to customize clone plugins

- skbase/base/_meta.py
This PR adds an `allow_empty` option in `_MetaObjectMixin._check_objects`, which allows for the edge case of empty list - this may be useful in some meta-estimators.
> [ENH] `allow_empty` option in `_MetaObjectMixin._check_objects`

- .all-contributorsrc
- skbase/utils/dependencies/_dependencies.py
- skbase/utils/dependencies/tests/test_check_dependencies.py
Fixes: https://github.com/sktime/sktime/issues/7517
Make "rc" python version recognizable during python version checking.
Introducing a parameter `prereleases=True`
The following code snipped now returns true:
```python
"3.11.0rc1" in SpecifierSet(">3.8", prereleases=True) 
```
No
On the tests regarding checking python versions.
> [BUG] Accepting prereleases as valid python version

- .all-contributorsrc
- skbase/tests/test_base.py
Fixes https://github.com/sktime/skbase/issues/170
refactored repetitive clone tests with pytest.mark.parametrize
No
> [ENH] refactor repetitive clone tests with pytest.mark.parametrize, fixes #170

- skbase/utils/deep_equals/_deep_equals.py
- skbase/utils/tests/test_deep_equals.py
fix https://github.com/sktime/skbase/issues/406
> [BUG] fix `deep_equals` for `pandas.Index`

- .github/workflows/wheels.yml
This PR removes macos pre-release tests in the release workflow, because there is a far lower concurrency limit on macos tests, and unix is tested already via ubuntu.
Macos is also still tested in the main CI triggered by pull requests.
> [MNT] remove macos pre-release tests in release workflow

- .github/workflows/test.yml
Updates the `nodevdeps` runner to `ubuntu-latest`, from a fixed version that is no longer supported.
> [MNT] update `nodevdeps` runner to latest `ubuntu`

- README.md
Corrects the macOS reference in the README.
> [DOC] correct macOS reference in README

- .github/workflows/update_contributors.yml
Removes the workflow dependency on the 3rd party GitHub workflow action `stefanzweifel/git-auto-commit-action`, by replacing it with a variation on a `git diff` call.
This is to enhance our security posture, as third party actions are possible security vulnerabilities - even if pinned, they can be  compromised (unlike python packages), see for instance the `tj-actions` compromise.
Copies action from https://github.com/sktime/sktime/pull/8369
> [MNT] remove `stefanzweifel/git-auto-commit-action` from all-contributors workflow

- skbase/utils/dependencies/_dependencies.py
This PR fixes the `_check_soft_dependencies` error message if the right packages are present but the version is wrong.
Mirror of https://github.com/sktime/sktime/pull/8430.
> [BUG] fix `_check_soft_dependencies` error message if version is wrong

- skbase/testing/test_all_objects.py
PR https://github.com/sktime/skbase/pull/428 forgot to update the docstring as well. This PR adds the missing docstring entry.
> [DOC] add missing docstring argument for `QuickTester.run_tests`

- .github/workflows/wheels.yml
- docs/source/user_documentation/changelog.rst
replaces the deprecated `windows-2019` runner with `windows-latest` in `wheels` release workflow
> [MNT] replace deprecated `windows-2019` runner with `windows-latest` in `wheels` release workflow
