.github/workflows/test.yml, .pre-commit-config.yaml
Fixes #22
The initial setup of CI_CD left off the branches that should execute a CI run when they are pushed to. This should only be the main branch and any branch starting with "release" (so we can use those branches to manage future releases).
I'm also removing the pre-commit hook to protect the main branch (b/c this is now turned on in Github).
No
=> Tweak CI Workflow

baseobject/_base.py
This brings `BaseObject` in line with `sktime` changes from https://github.com/alan-turing-institute/sktime/pull/2835
=> [ENH] Upgrade `set_params` to `sktime` state

.github/workflows/wheels.yml
This adds CD workflow needed for v0.1.0 release.
=> Add CD workflow to build, test and upload wheels to pypi

.github/workflows/wheels.yml
removes broken coverage code from windows release CI workflow
=> [ENH] remove broken coverage code from windows release CI workflow

.github/workflows/test.yml
Fixes #59
Makes Github Action version updates outlined in #59.
None.
Whether CI workflow is impacted.
None.
=> Update Github Action Versions

.github/workflows/test.yml, .github/workflows/wheels.yml, README.md, pyproject.toml
=> Add support for Python 3.11

skbase/testing/utils/_dependencies.py, skbase/testing/utils/tests/test_check_dependencies.py
Migrates improvements to `_check_soft_dependencies` from `sktime`:
* https://github.com/sktime/sktime/pull/3925
* https://github.com/sktime/sktime/pull/3955
=> [ENH] improvements to `_check_soft_dependencies`

skbase/tests/test_exceptions.py
Works partially towards #49.
Adds tests that `skbase`'s custom exceptions raise an error as expected.
No new dependency.
=> Test exceptions

docs/source/contribute/development/developer_guide.rst, docs/source/contribute/development/developer_guide/ci.rst, docs/source/contribute/development/developer_guide/coding_standards.rst, docs/source/contribute/development/developer_guide/creating_docs.rst, docs/source/contribute/development/developer_guide/dependencies.rst, docs/source/contribute/development/developer_guide/git_workflow.rst, docs/source/contribute/development/developer_guide/release_instructions.rst, docs/source/contribute/development/reviewer_guide.rst, docs/source/contribute/how_to_contribute.rst, docs/source/get_started.rst, docs/source/index.rst, docs/source/user_documentation/installation.rst
This contains documentation updates and fixes to be included in the 0.3.0 release. Should only have updated documentation files (no code files).
=> Doc updates prior to release v0.3.0

docs/source/contribute/development/developer_guide/release_instructions.rst
Fixes single typo in release instructions.
=> Fix minor typo in release_instructions.rst

CONTRIBUTORS.md, README.md, docs/source/_static/switcher.json, docs/source/about/governance.rst, docs/source/about/history.rst, docs/source/conf.py, docs/source/contribute/development/developer_guide/enhancement_proposal.rst, docs/source/contribute/development/developer_guide/release_instructions.rst, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
This PR includes the updated versions and release notes for the v0.3.0 release.
=> Release v0.3.0

docs/source/user_documentation/installation.rst
Fixes #132 
A new virtual environment should be created when installing the development version of `skbase`. The steps on how to do that using `conda` has been added.
None
- We should also update `.gitignore` to exclude `.idea/` (as a whole or as per [recommendation](https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore)) and `/api_reference/auto_generated/`.
=> [DOC] Update installation guide to build skbase in a virtual env

.gitignore
None
Makes minor updates to the .gitignore file (I believe @achieveordie may have suggested these somewhere).
None
=> [ENH] Add vs code settings and auto generated api area to .gitignore

docs/source/conf.py
This updates the slack link in the documentation to point to the ``skbase`` slack workspace.
=> [MNT] Update slack to point to skbase workspace

README.md, docs/source/_static/switcher.json, docs/source/get_started.rst, docs/source/user_documentation/changelog.rst, docs/source/user_documentation/installation.rst, pyproject.toml, skbase/__init__.py, skbase/base/_pretty_printing/_pprint.py
Release 0.4.0
* changelog
* version bump
* package name
* linting
=> Release 0.4.0

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml
Release 0.4.1
* changelog
* version bump
=> Release 0.4.1

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml
Release 0.4.2
* changelog
* version bump
=> Release 0.4.2

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml
Release 0.4.3
* changelog
* version bump
=> Release 0.4.3

docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml
Release 0.4.4
* changelog
* version bump
=> Release 0.4.4

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml
Release 0.4.5
* changelog
* version bump
=> Release 0.4.5

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.4.6
* changelog
* version bump
=> Release 0.4.6

.github/workflows/test.yml, .github/workflows/wheels.yml, README.md, docs/source/_static/switcher.json, docs/source/get_started.rst, docs/source/user_documentation/changelog.rst, docs/source/user_documentation/installation.rst, pyproject.toml
Fix wheel name in release workflow
=> Release 0.5.0 - fix wheel name

skbase/utils/deep_equals.py
Fixes a single precommit linting issue from the new pre-commit versions in PR https://github.com/sktime/skbase/pull/205
=> [MNT] fix linting issue from newest pre-commit versions

skbase/base/_meta.py
Upstream version of `sktime` bugfix https://github.com/sktime/sktime/pull/4633
=> [BUG] fix for `get_fitted_params` in `_HeterogenousMetaEstimator`

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.5.2
* changelog
* version bump
=> Release 0.5.2

pyproject.toml
This PR updates the dependency versions in the `doc` dependency set and sets upper bounds for them.
=> [MNT] update dependency versions in `doc` dependency set and set upper bounds

pyproject.toml
adds back accidentally deleted `sphinx-panels` dependency in https://github.com/sktime/skbase/pull/226
=> [MNT] add back accidentally deleted `sphinx-panels`

.github/dependabot.yml
This PR activates `dependabot` for version updates and maintenance.
=> [MNT] activate `dependabot` for version updates and maintenance

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.6.1
* changelog
* version bump
=> Release 0.6.1

docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.6.2
* changelog
* version bump
=> Release 0.6.2

README.md
Updates readme witih forgotten 0.6.2 reference
=> [DOC] readme - version 0.6.2 update

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.7.1
* changelog
* version bump
=> Release 0.7.1

docs/source/user_documentation/changelog.rst
=> [DOC] lint changelog

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.7.2
* changelog
* version bump
=> Release 0.7.2

docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.7.3
* changelog
* version bump
=> Release 0.7.3

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.7.3 - forgotten update in readme
=> Release 0.7.3 - forgotten update in readme

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.7.4
* changelog
* version bump
=> Release 0.7.4

docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.7.5
* changelog
* version bump
=> Release 0.7.5

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.7.6
* changelog
* version bump
=> Release 0.7.6

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.7.8
* changelog
* version bump
=> Release 0.7.8

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.8.0
* changelog
* version bump
=> Release 0.8.0

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.8.1
* changelog
* version bump
=> Release 0.8.1

skbase/tests/conftest.py, skbase/utils/dependencies/_dependencies.py
This PR syncs the dependency checker utilities with `sktime`.
=> [ENH] sync dependency checkers with `sktime`

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.8.2
* changelog
* version bump
=> Release 0.8.2

skbase/tests/conftest.py, skbase/utils/stderr_mute.py, skbase/utils/tests/test_std_mute.py
Add stderr context manager.
related: https://github.com/sktime/sktime/pull/6891, https://github.com/sktime/sktime/issues/6653
=> [ENH] StderrMute

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.8.3
* changelog
* version bump
=> Release 0.8.3

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.9.0
* changelog
* version bump
=> Release 0.9.0

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.10.0
* changelog
* version bump
=> Release 0.10.0

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.10.1
* changelog
* version bump
=> Release 0.10.1

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.11.0
* changelog
* version bump
=> Release 0.11.0

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.12.0
* changelog
* version bump
=> Release 0.12.0

skbase/tests/conftest.py, skbase/utils/dependencies/_dependencies.py
This PR syncs dependency checker utilities with `sktime`.
=> [ENH] sync dependency checker utilities with `sktime`

.all-contributorsrc, README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.12.1
* changelog
* version bump
=> Release 0.12.1

skbase/_nopytest_tests.py
Fixes a minor typo in a code comment.
=> [DOC] minor typo fix in code comment

skbase/base/_base.py, skbase/testing/test_all_objects.py
Formatting changes in docstrings and typo fixes.
=> [DOC] minor documentation fixes

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.12.2
* changelog
* version bump
=> Release 0.12.2

.github/workflows/wheels.yml, docs/source/user_documentation/changelog.rst
Updates the release runner to `ubuntu-latest`
=> [MNT] Update release runner to `ubuntu-latest`

skbase/testing/test_all_objects.py
This PR adds verbose output to `QuickTester`, informing the user on passed and failed tests, if `raise_exceptions=True`.
As the utility immediately raises on failure, the output needs to be conditioned directly on try/except of execution of the individual tests, hence a `verbose` parameter is added in `QuickTester.run_tests` to achieve this result.
Mirror of https://github.com/sktime/sktime/pull/8047
=> [ENH] `QuickTester` verbose output on passed and failed tests if `raise_exceptions=True`

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.12.5
* changelog
* version bump
=> Release 0.12.5

README.md, skbase/base/_clone_plugins.py, skbase/tests/conftest.py, skbase/utils/dependencies/__init__.py, skbase/utils/dependencies/_dependencies.py, skbase/utils/dependencies/_import.py, skbase/utils/dependencies/tests/test_safe_import.py
updates `_safe_import` to the state in `sktime` and `pytorch_forecasting`
=> [ENH] update `_safe_import` to state in `sktime` and `pytorch_forecasting`

README.md, docs/source/_static/switcher.json, docs/source/user_documentation/changelog.rst, pyproject.toml, skbase/__init__.py
Release 0.12.6
* changelog
* version bump
=> Release 0.12.6
